name: Generar Snake
on:
  push:  # Cualquier push a cualquier rama
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4 
      
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          commit_message: "feat: Actualizar Snake Game Contribution Grid"
          files: dist/*
